import type { Metadata } from "next";
import "./globals.css";
import { WebVitals } from './components/web-vitals'
import { Noto_Sans_JP } from "next/font/google";
import Header from "./components/header";

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-noto-sans-jp',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <WebVitals />
      <body className={notoSansJP.className}><Header /><main className="min-h-screen flex-col p-24 max-w-screen-2xl m-auto">{children}</main></body>
    </html>
  );
}